Repository nchaulet/node-geocoder, pull requests merged in 2022-02, with the labels that each got.

#324 Improving error handling
  .jshintrc
  lib/geocoder/heregeocoder.js
  lib/httpadapter/fetchadapter.js
Labels: enhancement

#332 Remove http adapters
  CHANGELOG.md
  README.md
  lib/geocoderfactory.js
  lib/httpadapter/httpadapter.js
  lib/httpadapter/httpsadapter.js
  lib/httpadapter/requestadapter.js
  package.json
  test/geocoder/geocodiogeocoder.test.js
  test/geocoder/googlegeocoder.test.js
  test/geocoder/heregeocoder.test.js
  test/geocoder/mapquestgeocoder.test.js
  test/geocoder/mapzengeocoder.test.js
  test/geocoder/openmapquestgeocoder.test.js
  test/geocoder/smartystreetsgeocoder.test.js
  test/geocoderfactory.test.js
  test/httpadapter/httpadapter.test.js
Labels: enhancement, breaking-changes

#333 Remove deprecated option from here geocoder
  lib/geocoder/heregeocoder.js
  lib/geocoder/mapboxgeocoder.js
Labels: breaking-changes
